/**
 * UI 文字統一管理
 * 規範：index.html、App.vue、所有元件嚴禁出現硬編碼中文字串
 * 所有面向使用者的文字必須從這裡引用
 */

export const UI_STRINGS = {
  APP: {
    title: '豐盛幫手',
    version: 'v0831.02',
    dataTimePrefix: '資料 ',
    realtimePrefix: '即時 ',
  },

  MARKET_REGIME: {
    SAFE: { badge: '多頭順風', title: '市場多頭順風，可執行操作' },
    CAUTION: { badge: '震盪回檔', title: '指數破 5MA，建議減量防守' },
    DANGER: { badge: '系統性風險', title: '破月線，建議空手觀望' },
  },

  SCREENER: {
    updateBtn: '更新',
    updatingBtn: '更新中…',
    resultCount: (n) => `符合 ${n} 檔`,
    noResult: '無符合條件的個股',
    suggestions: {
      BOTTOM_REVERSAL: '可嘗試將【月線乖離率】上限放寬至 0%，或將【當日成交量】調降至 500 張，以探索更多潛力標的。',
      BOTTOM_CONSOLIDATION: '可嘗試取消勾選【量縮洗盤】或將【當日三線價差】上調到 5%，以探索更多潛力標的。',
      MOMENTUM_BREAKOUT: '可嘗試將【當日成交量】調降至 500 張，或將【當日三線價差】上限放寬到 10%-12%，亦可將【前一日三線價差】微調至 5%，以探索更多潛力標的。',
      TREND_PULLBACK: '可嘗試將【月線乖離率】放寬至 0%-15%，或將【5MA 乖離率】下修到 -5%，以探索更多潛力標的。',
      WASHOUT_IGNITION: '可嘗試取消勾選【K > D 黃金交叉】，或將【KD 區間】上限放寬至 75，亦可將【當日成交量】調降至 500 張，以探索更多潛力標的。',
    },



    matchedStrategy: (names) => `🎯 命中策略：【${names}】`,
    noMatchedStrategy: '── 全市場常態個股（未觸發特定策略）',
    matchedCondition: (modeName) => `💡 符合【${modeName}】策略條件`,
    unmatchedReasonPrefix: '淘汰原因：',
    expandUnmatched: (n) => `查看未符合個股 (${n} 檔) 與淘汰原因`,
    collapseUnmatched: (n) => `收合未符合個股 (${n} 檔)`,
    disposed: '處置',
    lastUpdated: (t) => `更新於 ${t}`,
  },

  SEARCH: {
    placeholder: '搜尋股票代號或名稱 (例如 2330 或 台積)...',
    clear: '清除搜尋',
    searchingFor: (q) => `搜尋「${q}」`,
    searchResultCount: (n) => `搜尋符合 ${n} 檔`,
    searchNoResult: '查無符合代號或名稱的個股',
    matchedGroupTitle: '符合策略個股',
    unmatchedGroupTitle: '未符合本策略（含淘汰原因）',
  },

  TIME_MACHINE: {
    title: '時光機',
    subtitle: '時光倒流至近 5 個交易日，驗證各策略歷史選股表現',
    today: '最新行情',
    daysAgo: (n) => `${n} 天前`,
    day1Ago: '昨日 (T-1)',
    day2Ago: '2天前 (T-2)',
    day3Ago: '3天前 (T-3)',
    day4Ago: '4天前 (T-4)',
    day5Ago: '5天前 (T-5)',
    activeNotice: (n) => `⏳ 時光倒流中：正在回測 ${n} 個交易日前之全市場歷史數據`,
  },


  STOCK_TABLE: {
    headers: {
      code: '代號',
      name: '名稱',
      price: '現價',
      change: '漲跌',
      changePct: '漲跌幅',
      volume: '量(張)',
      ma5: '5MA',
      ma20: '月線',
      bias5: '5MA乖離',
      bias20: '月乖離',
      kd: 'KD',
      sparkline: '近10日',
    },
  },

  KD_STATUS: {
    golden: '黃金交叉',
    death: '死亡交叉',
    hot: '超買過熱',
    low: '低檔整理',
    mid: '中檔震盪',
  },

  CATEGORY_TAGS: {
    '0050': '0050',
    '0051': '0051',
    'ForeignBuy': '外資買',
    'ForeignBuy1D': '外資1D',
    'ForeignBuy3D': '外資3D',
    'MajorBuy': '主力買',
    'MajorBuy1D': '主力1D',
    'MajorBuy3D': '主力3D',
    'SitcaBuy': '投信買',
    'SitcaBuy3D': '投信3D',
    'SitcaBuy5D': '投信5D',
    'Top100': '量大',
    'ValueTop': '值大',
    'TurnoverRate': '週轉',
    '半導體': '半導體',
  },

  SELL_WARNINGS: {
    foreign1D: '外資賣1D',
    foreign3D: '外資賣3D',
    sitca3D: '投信賣3D',
    major1D: '主力賣1D',
    major3D: '主力賣3D',
    foreign: '外資賣超',
    major: '主力賣超',
    sitca: '投信賣超',
    foreignSitca: '法人賣超',
    foreignMajor: '外資/主力賣超',
    sitcaMajor: '投信/主力賣超',
    all: '法人/主力賣超',
  },
  METRICS: {
    ma5: 'MA5',
    ma10: 'MA10',
    ma20: 'MA20',
    ma60: 'MA60',
    volume: '量(張)',
    mv5: 'MV5',
    mv10: 'MV10',
    kd: 'KD',
    expectedProfit: '預期純利',
    ceiling: '關卡',
  },

  ACTIONS: {
    copy: '複製',
    copied: '已複製',
    chips: '籌碼',
    bullbear: '多空',
    margin: '資券',
    afterMarket: '盤後',
    details: '詳情',
  },

  PANEL: {
    title: '篩選條件',
    allTab: '全部',
    allDescription: '全市場監控名單總覽，未套用特定策略過濾條件',
    resetBtn: '重設為預設值',
    adjustParams: '調整參數',
    collapseParams: '收合參數',
    customized: '已自訂',
    matchSummary: (n, total) => `符合 ${n} / ${total} 檔`,
    moduleMa: '均線與位階過濾',
    moduleVol: '量能與流動性',
    maSupport: '均線支撐',
    maAboveBoth: '(嚴) 同時站穩 5MA 與 10MA',
    maAboveAny: '(寬) 站穩 5MA 或 10MA',
    maAbove5ma: '(寬) 站上 5MA',
    maAboveNone: '無限制',
    ma20Rising: '月線斜率向上 (今日 20MA > 昨日 20MA)',
    convergence: '當日三線價差',
    convergenceThreshold: (n) => `當日三線價差 ≤ ${n}%`,
    prevConvergence: '前一日三線價差',
    prevConvergenceThreshold: (n) => `前一交易日三線價差 ≤ ${n}%`,
    bias5Range: '5MA 乖離率 (%)',
    bias20Range: '月線乖離率 (%)',
    minVolume: '當日成交量',
    minVolumeThreshold: (n) => `當日成交量 ≥ ${n} 張`,
    notDisposed: '排除處置股',
    aboveMa60: '站穩季線防身 (收盤價 ≥ 60MA)',
    volContraction: '量縮洗盤 (量 < 5日均量)',
    tightConsolidation: '狹幅震盪打底 (漲跌幅 -1.5% ~ +1.5%)',
    volPullback: '量縮回踩 (量 < 5日量均 或 < 昨日量)',
    prevVolContraction: '昨日成交量 < 昨日 5 日均量 (MV5)',
    volExpansion: '當日帶量攻擊 (當日量 > 5日量均)',
    volExpansionPullback: '洗盤後帶量攻擊 (當日量 > 5日量均)',
    volExpansionReversal: '低檔爆量攻擊 (當日量 > 5日量均)',
    redCandle: '實體攻擊紅 K (收盤 > 開盤 且 漲幅 ≥ 1.5%)',
    redCandle2Pct: '實體攻擊紅 K (收盤 > 開盤 且 漲幅 ≥ 2%)',
    redCandleReversal: '實體反轉紅 K (收盤 > 開盤 且 漲幅 ≥ 2%)',
    avoidLongBlack: '排除長黑倒貨',
    avoidUpperShadow: '排除長上影線避雷針 (上影線 ≤ 實體紅K一半)',
    kdFilter: 'KD 動能區過濾',
    kdMomentumAttack: 'KD 強勢攻擊區 (K 值 > 50 且 K > D 黃金交叉)',
    kdGoldenCross: 'K > D 黃金交叉',
    to: '至',
  },

  FILTER_REASONS: {
    passed: '符合篩選條件',
    invalidCode: '非有效股票代碼',
    bias5Below: (min, val) => `5MA 乖離過低 (${val}% < ${min}%)`,
    bias5Above: (max, val) => `5MA 乖離過高 (${val}% > ${max}%)`,
    bias20Below: (min, val) => `20MA 乖離過低 (${val}% < ${min}%)`,
    bias20Above: (max, val) => `20MA 乖離過高 (${val}% > ${max}%)`,
    belowMa60Failed: '未站穩季線防身 (現價 < 60MA)',
    maAboveBothFailed: '未同時站穩 5MA 與 10MA',
    maAboveAnyFailed: '未站穩 5MA 或 10MA',
    maAbove5maFailed: '未站上 5MA',
    convergenceFailed: (max, val) => `當日三線價差過大 (${val}% > ${max}%)`,
    prevConvergenceFailed: (max, val) => `前一日三線價差過大 (${val}% > ${max}%)`,
    ma20NotRising: '月線斜率未向上 (今日 20MA ≤ 前一日 20MA)',
    volumeBelow: (min, val) => `成交量未達門檻 (${val} 張 < ${min} 張)`,
    isDisposedStock: '此為處置股票 (關禁閉中)',
    volContractionFailed: '當日未達量縮標準 (成交量 ≥ 5日量均)',
    strictVolContractionFailed: '未達嚴格量縮標準 (成交量 > 5日量均 × 0.8)',
    tightConsolidationFailed: (val) => `漲跌幅超出狹幅震盪打底區間 (${val}%)`,
    volPullbackFailed: '未達量縮回踩標準 (未低於 5日量均或昨日量)',

    prevVolContractionFailed: '昨日未達量縮標準 (昨日量 ≥ 昨日5日量均)',
    volExpansionFailed: '未達帶量攻擊標準 (成交量 ≤ 5日量均)',
    redCandleFailed: '未達實體攻擊紅 K 標準',
    avoidLongBlackFailed: '觸發長黑倒貨型態 (實體黑K跌幅 ≥ 1.5% 且收最低點附近)',
    avoidUpperShadowFailed: '觸發避雷針型態 (上影線長度超過實體紅 K 一半)',
    kdOutOfRange: (min, max, val) => `KD 未處於指定區間 (K=${val} 不在 ${min}~${max})`,
    kdCrossFailed: 'KD 未形成多頭排列 (K ≤ D)',
  },


  API_SETTINGS: {
    modalTitle: '行情 API 設定',
    modalDesc: '請輸入 GCP Cloud Function 即時行情代理微服務網址。',
    urlLabel: 'GCP Function 網址',
    urlPlaceholder: 'https://asia-east1-PROJECT.cloudfunctions.net/market-data-proxy',
    saveBtn: '儲存設定',
    clearBtn: '清除設定',
    closeBtn: '關閉',
    savedToast: '已儲存行情 API 網址',
    clearedToast: '已清除行情 API 網址',
    emptyNotice: '尚未設定行情 API 網址，請先點擊設定',
  },

  REALTIME: {
    fetchBtn: '更新',
    fetchingBtn: '更新中…',
    fetchSuccess: (count) => `已更新 ${count} 筆即時行情`,
    missingWarning: (missingCount) => `即時行情有 ${missingCount} 筆資料未回傳，嚴禁使用舊資料補齊，請重新整理或稍候再試`,
    fetchFailed: '連線行情 API 失敗，請檢查網址、CORS 或網路狀態',
    lastUpdated: (t) => `即時更新於 ${t}`,
  },
}

